### ISSUE TITLE
Solver broken after error encountered 

### ISSUE THREAD

**Issue by mishaelnuh** [HALRobotics/Beta#78] opened 2020-11-24 13:49 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in a minimal file that you can share if needed.
    * Checked that your issue isn't already filed: https://github.com/HALRobotics/Beta/issues?utf8=%E2%9C%93&q=is%3Aissue

### Description

Solver does not seem to properly run after an error is encountered from the procedure input of the controller. Toggling `solve` input or reinitialising the component does not seem to solve it. Adding new solve component fixes the issue. Closing and opening the file fixes the issue.

### Steps to Reproduce

1. Create a simulation with 2 or more procedures combined (using the merge GH component). <img width="999" alt="image" src="https://user-images.githubusercontent.com/45694155/100102064-ff4b6e80-2e5a-11eb-83b6-2fa977bcf408.png">
2. Toggle the simulation on.
3. Unflatten one of the procedure input for the merge component causing error. <img width="1015" alt="image" src="https://user-images.githubusercontent.com/45694155/100102106-0c685d80-2e5b-11eb-94fd-710d9bc0723e.png">
4. Undo error. <img width="1020" alt="image" src="https://user-images.githubusercontent.com/45694155/100102137-138f6b80-2e5b-11eb-825d-7290432edc1f.png">

**Expected behavior:** The solve component should continue to run after the error is fixed.

**Actual behavior:** Execute component outputs error: "No executable procedures were found.". Reinitialising or toggling the solver input does not solve the issue. Placing a new solve component fixes this.

**Reproduces how often:** 100% reproducibility.

### Versions
1.3.20-beta HAL framework
Windows 10 VM using Parallels 16 on MacOS 11.0.1

### Additional Information
GH file to reproduce bug: [combine bug.zip](https://github.com/HALRobotics/Beta/files/5590233/combine.bug.zip)

**Comment by theonlytruth** [comment] 2020-11-25 17:05
I see the error message "No executable procedures were found." also often. I think the reason were other errors but also solving those didn't help to get the execute to run again. For me it worked to copy everything in a new file or restart the software.

Please look for a solution because this is for me the only thing which feels very "beta".

**Comment by tristangobin** [comment] 2020-11-25 17:11
Thank you to report it. We are looking into it closely.

TEMPORARY WORK AROUND :
It is not necessary to restart grasshopper or rhino. It should be enough to close the file and reopen it. Be sure that all files are closed. Sometime grasshopper open twice the same file.

**Comment by sebandraos** [comment] 2020-12-04 10:50
@mishaelnuh Thanks for reporting this, it isn't something we had noticed internally. We are working on fix at the moment but I just wanted to mention a useful little trick that would simplify your file: Passing a Point into a floating Target parameter (not full component) will automatically give you a Target facing downwards.
@theonlytruth Our initial exploration of this bug looks to be very closely related to inadvertently creating multiple Controllers and passing them to the Solver component. If you come across this issue again and you don't think it follows this same pattern, please try and send us a file that reproduces the bug so that we can fix it in your case too.
Thanks again to both of you for helping making the HAL Robotics Framework better for everyone

**Comment by thibaultschwartz** [comment] 2020-12-04 13:48
This issue is fixed in the next update. Please reopen if necessary.

**Closed** 2020-12-04 13:48 UTC
Labels: bug
