### ISSUE TITLE
"PCSDK not started" error message in Controller Configurator

### ISSUE THREAD

**Issue by CQuinonez01** [HALRobotics/Beta#116] opened 2021-10-07 16:12 UTC
### Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in a minimal file that you can share if needed.
    * Checked that your issue isn't already filed: https://github.com/HALRobotics/Beta/issues?utf8=%E2%9C%93&q=is%3Aissue

### Description

[Description of the issue]
![HAL Issue](https://user-images.githubusercontent.com/92111192/136423086-941af2ee-e3a5-49be-899d-6baeb78bc569.JPG)
I don't understand why this happened. I uninstalled everything and added all the extensions that I did the first time and it happened again.

**Comment by sebandraos** [comment] 2021-10-07 16:58
In which case, this looks like a duplicate of this issue: https://github.com/HALRobotics/Beta/issues/107
I would recommend using the workaround I described in my first message then because if our software hasn't changed and RobotStudio hasn't changed then it sounds like a local machine configuration issue that's going to be very complicated to get to the bottom of. RobotWebServices is designed to avoid this kind of issue so I would head down that route.

**Closed by sebandraos** 2021-10-07 16:58 UTC
