### ISSUE TITLE
I have got an empty list in the robot component  

### ISSUE THREAD

**Issue by madil4** [HALRobotics/Beta#27] opened 2018-06-03 00:31 UTC
I have followed the installation procedure precisely but I have got an empty list when I double clicked the Robot component.

I'm running windows 10, and Rhino 5 640-bit.

![sdf](https://user-images.githubusercontent.com/3858873/40882015-2e446c36-66d6-11e8-90c3-567366abdf0d.JPG)

**Comment by sebandraos** [comment] 2018-06-03 07:55
Possible duplicate of #21 and therefore #22 . Can you please try deactivating all other grasshopper plugins and seeing if that works? Please also let us know which versions of the HAL Robotics Framework components you have installed. You can see this in the HAL->About menu in grasshopper.

**Comment by madil4** [comment] 2018-06-03 15:06
It works now after removing Lunchbox plugin,  I'm wondering if the robot ABB IRB 6650 will be supported soon?

**Comment by thibaultschwartz** [comment] 2018-06-04 07:47
Yes the IRB 6xxx series presets will be added very soon. I close this issue and add a reference to #22 . Thanks for reporting this bug.

**Closed by thibaultschwartz** 2018-06-04 07:47 UTC
